"$schema" = 'https://starship.rs/config-schema.json'

format = """
[┌─](bold fg:overlay0)$username$hostname$directory$git_branch$git_status$fill$status$cmd_duration$time
$character"""

palette = 'smt'

[palettes.smt]
blue = "#5f87af"
green = "#87af5f"
yellow = "#d7af5f"
red = "#d75f5f"
cyan = "#5fafaf"
fg = "#d0d0d0"
muted = "#8a8a8a"
overlay0 = "#5f5f5f"
bg = "#1c1c1c"

[username]
show_always = false
style_user = "bold fg:green"
style_root = "bold fg:red"
format = "[$user]($style)"

[hostname]
ssh_only = true
style = "fg:yellow"
format = "[@$hostname]($style) "

[directory]
style = "bold fg:blue"
format = " [${path}]($style)[$read_only]($read_only_style)"
home_symbol = "~"
truncation_length = 4
truncation_symbol = "../"
read_only = " !"
read_only_style = "fg:red"
truncate_to_repo = false

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = "git:"
style = "fg:green"
format = " on [$symbol$branch]($style)"

[git_status]
style = "fg:yellow"
format = "([$all_status$ahead_behind]($style))"

[nodejs]
symbol = ""
style = "fg:cyan"
format = "[ via $symbol$version]($style)"

[c]
symbol = " "
style = "fg:cyan"
format = "[ via $symbol$version]($style)"

[rust]
symbol = ""
style = "fg:cyan"
format = "[ via $symbol$version]($style)"

[golang]
symbol = ""
style = "fg:cyan"
format = "[ via $symbol$version]($style)"

[php]
symbol = ""
style = "fg:cyan"
format = "[ via $symbol$version]($style)"

[java]
symbol = " "
style = "fg:cyan"
format = "[ via $symbol$version]($style)"

[kotlin]
symbol = ""
style = "fg:cyan"
format = "[ via $symbol$version]($style)"

[haskell]
symbol = ""
style = "fg:cyan"
format = "[ via $symbol$version]($style)"

[python]
symbol = ""
style = "fg:cyan"
format = "[ via $symbol$version]($style)"

[docker_context]
symbol = ""
style = "fg:cyan"
format = "[ via $symbol$context]($style)"

[time]
disabled = false
time_format = "%R"
style = "fg:muted"
format = "[ $time]($style)"

[fill]
symbol = " "

[status]
disabled = false
style = "bold fg:red"
symbol = "✘ "
success_symbol = ""
format = "[ $symbol$status]($style)"
map_symbol = true

[cmd_duration]
min_time = 1500
style = "fg:muted"
format = "[ took $duration]($style)"

[line_break]
disabled = false

[character]
disabled = false
success_symbol = "[└─❯](bold fg:blue)"
error_symbol = "[└─❯](bold fg:red)"
vimcmd_symbol = "[└─❮](bold fg:green)"
vimcmd_replace_one_symbol = "[└─❮](bold fg:yellow)"
vimcmd_replace_symbol = "[└─❮](bold fg:yellow)"
vimcmd_visual_symbol = "[└─❮](bold fg:cyan)"
